#!/usr/bin/env bash
# Script: 0-world_wide_web
# Description: Display information about subdomains of a given domain.

# Function to display information about a subdomain
get_subdomain_info() {
    sub_domain=$1
    record_type=$(dig $sub_domain | awk '/ANSWER SECTION/ {getline; print $4}')
    destination=$(dig $sub_domain | awk '/ANSWER SECTION/ {getline; print $5}')
    echo "The subdomain $sub_domain is a $record_type record and points to $destination"
}

# Check if the correct number of arguments is provided
if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

# Domain name
domain=$1

# Check if subdomain is specified
if [ "$#" -eq 1 ]; then
    # Display information for default subdomains
    get_subdomain_info "www.$domain"
    get_subdomain_info "lb-01.$domain"
    get_subdomain_info "web-01.$domain"
    get_subdomain_info "web-02.$domain"
elif [ "$#" -eq 2 ]; then
    # Display information for specified subdomain
    get_subdomain_info "$2.$domain"
fi
